-- Settings
local opt = vim.opt

opt.encoding = 'utf-8'
opt.fileencoding = 'utf-8'
opt.fileencodings = { 'utf-8', 'iso-2022-jp', 'euc-jp', 'sjis' }
-- opt.fileformats = { 'unix', 'doc', 'mac' }
opt.ttimeout = true
opt.timeoutlen = 500
opt.ttimeoutlen = 50
opt.backup = false
opt.swapfile = false
-- opt.nowritebackup = true
-- opt.noswapfile = true
-- opt.nobomb = true
opt.clipboard = 'unnamedplus'
opt.autoread = true
opt.hidden = true
opt.textwidth = 100
opt.wrap = true
opt.scrolloff = 5
opt.wildignore = { '*.o', '*‾', '*.pyc' }
opt.wildmode = 'longest,full'
opt.whichwrap:append '<,>,h,l'
opt.inccommand = 'split'
opt.lazyredraw = true
opt.re = 1
opt.ttyfast = true
opt.showmatch = true
opt.matchtime = 1
opt.ignorecase = true
opt.smartcase = true
opt.tabstop = 2
opt.splitright = true
opt.termguicolors = true
opt.syntax = 'on'
opt.softtabstop = 0
-- opt.softtabstop = 2
opt.expandtab = true
opt.shiftwidth = 2
opt.number = true
opt.relativenumber = true
opt.ruler = true
opt.numberwidth = 1
opt.breakindent = true
opt.showcmd = true
opt.cmdheight = 2
opt.smartindent = true
opt.laststatus = 3
opt.showmode = false
opt.shada = [['20,<50,s10,h,/100]]
opt.shortmess:append 'c'
opt.joinspaces = false
opt.guicursor = [[n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50]]
opt.updatetime = 100
-- opt.cursorhold_updatetime = 150
opt.conceallevel = 2
opt.concealcursor = 'nc'
opt.previewheight = 5
opt.undofile = true
opt.synmaxcol = 500
-- opt.display = 'msgsep'
opt.display = 'lastline'
opt.cursorline = true
-- opt.cursorcolumn = true
opt.cursorlineopt = "both"
opt.modeline = true
opt.modelines = 10
-- opt.mouse = 'nivh'
opt.mouse = 'a'
opt.signcolumn = 'yes:1'
opt.title = true
opt.titleold = 'Terminal'
opt.virtualedit = 'onemore'
opt.visualbell = true
-- opt.list.listchars = 'tab:¥笆ｸ¥-'
opt.list = true
opt.listchars:append "space:⋅"
-- opt.listchars:append "eol:↴"
opt.history = 10000
opt.hlsearch = true
opt.incsearch = true
opt.magic = true
opt.wrapscan = true
opt.inccommand = 'split'
opt.pumblend = 0
opt.pumheight = 10
opt.backspace = { 'indent', 'eol', 'start' }
opt.helplang = 'ja'
opt.autoindent = true
opt.background = 'dark'
opt.spelllang = { 'en' }
opt.spellsuggest = { 'best', 9 }
opt.shell = '/opt/homebrew/bin/fish'
